dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:

  matrix:
    - SERVICE="orthanc" ARCH_TAG="amd64"
#    - SERVICE="orthanc" ARCH_TAG="arm32v7"
#    - SERVICE="orthanc" ARCH_TAG="arm64v8"


before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  # Build image
  - docker-compose build $SERVICE-$ARCH_TAG

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # manifest and push
  - python3 manifest-it.py orthanc-xarch.manifest.yml

