# Pass in ORX_BRANCH, ORX_TAG

version: '3'

services:

  orthanc-amd64:
    build:
      context: .
      args:
        ORX_BRANCH: $ORX_BRANCH
    image: derekmerck/orthanc:$ORX_TAG-amd64

  orthanc-arm32v7:
    build:
      context: .
      args:
        RESIN_ARCH: raspberrypi3
        ORX_BRANCH: $ORX_BRANCH
    image: derekmerck/orthanc:$ORX_TAG-arm32v7
