version: '3'

services:

  orthanc-amd64:
    build:
      context: .
    image: derekmerck/orthanc:amd64

  orthanc-arm32v7:
    build:
      context: .
      args:
        RESIN_ARCH: raspberrypi3
    image: derekmerck/orthanc:arm32v7

  orthanc-arm64v8:
    build:
      context: .
      args:
        RESIN_ARCH: generic-aarch64
    image: derekmerck/orthanc:arm64v8
