# Pass in ORX_BRANCH, ORX_TAG, "default" is master

version: '3'

services:

  orthanc-amd64:
    build:
      context: .
      args:
        ORX_BRANCH: $ORX_BRANCH
    image: derekmerck/orthanc:$ORX_TAG-amd64

  orthanc-arm32v7:
    build:
      context: .
      args:
        RESIN_ARCH: raspberrypi3
        ORX_BRANCH: $ORX_BRANCH
    image: derekmerck/orthanc:$ORX_TAG-arm32v7

  orthanc-arm64v8:
    build:
      context: .
      args:
        RESIN_ARCH: jetson-tx2
        ORX_BRANCH: $ORX_BRANCH
    image: derekmerck/orthanc:$ORX_TAG-arm64v8
